skip_commits:
  message: /((Create.*\.md)|(Update.*\.md))/

version: 0.0.0.{build}

configuration: Release

environment:
  sourcesFolder: src\dotnet
  solutionName: adsp.sln
  projectName: ADSP

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

before_build:
  - cd %sourcesFolder%
  - nuget restore
  - cd ..\..

build:
  verbosity: minimal  
  project: $(sourcesFolder)\$(solutionName)
  publish_nuget: true
  publish_nuget_symbols: true
